### ISSUE TITLE
Sound not always working

### ISSUE THREAD

**Issue by vikke1234** [Loze-Put/hunllef-helper#10]
It's pretty hit and miss if the sound comes or not.

**Comment by Loze-Put** [comment]
Could you provide a log file of a game session where this issue occured? You can find a log file inside the logs folder within your .runelite directory. Select a client log file with a date on which the issue occured. I would also like to know which operating system you use.

**Comment by vikke1234** [comment]
Sure, I'm on Linux (Manjaro) using KDE, as for the log file here you go.

[client.log](https://github.com/Loze-Put/hunllef-helper/files/7318527/client.log)

**Comment by Loze-Put** [comment]
Unfortunately the log does not contain an error from this plugin. Could you try another one? For instance client_2021-10-10.0.log if you used the plugin on 10 October.

**Comment by vikke1234** [comment]
[client_2021-10-10.0.log](https://github.com/Loze-Put/hunllef-helper/files/7322602/client_2021-10-10.0.log)
Here you go, hopefully it has something usefull!

**Comment by Loze-Put** [comment]
Unfortunately the log does not contain any useful information. The plugin should be logging any errors that occur while trying to play audio. Does the audio issue only occur while using this plugin, or does it also occur for the entire RuneLite application or any other plugins? And when the issue occurs, is it the sound completely broken, or do some sounds play while others don't?

**Comment by vikke1234** [comment]
Hmm, it seems it's working more consistently now but every now and then it still fails to say the switches. It's only the plugin that fails to output sound, I tried to have osrs sounds on and that music works.
