### ISSUE TITLE
Custom audio

### ISSUE THREAD

**Issue by jay194** [Loze-Put/hunllef-helper#11]
Hey, this may sound lame but is it possible to add custom audio for each the one, two, range and mage. I tried building the jar locally with replaced audio files and placing the plugin into runelite folder but not sure why it would never work. Maybe runelite only pulls from git hub. Not sure how it works. But would be funny if we could change the audo.

**Comment by Loze-Put** [comment]
Hello,
I have been thinking about adding sound packs or the ability to use custom audio for a while. I do think it is a valuable feature for some people. I will give it a shot when I have time.
It is indeed not possible to build your own jar and add it to RuneLite. The only way you can currently do this is by downloading this repository, replacing the audio files, and run the plugin as a plugin in development.

**Comment by orlp** [comment]
I would love this feature as well. In particular one option I would like is for the 3-2-1 to be replaced with just various beeps. When doing 5:1 counting it's particularly distracting to have someone shout different numbers at you.

**Comment by Loze-Put** [comment]
I have implemented custom audio in #13
