### ISSUE TITLE
Caching audio files

### ISSUE THREAD

**Issue by orlp** [Loze-Put/hunllef-helper#12]
If I read the code right, this plugin reads the audio file from disk everytime it is played. Would it be possible to cache them in memory instead? Sometimes (I can't always reproduce) there appears to be lag associated with this plugin whenever it plays audio:

https://user-images.githubusercontent.com/202547/151666979-f67b69ce-c5cc-46cd-bf60-b247aa3df4ed.mp4

**Comment by Loze-Put** [comment]
I have noticed this fps drop recently. I'm not sure if it has always been there. It is correct that the code reads the audio files every time it plays. I will update it to cache the files instead and see if that fixes the issue.

**Comment by Loze-Put** [comment]
This issue has been resolved in #13
