### ISSUE TITLE
Feature Request - Color Tag hunlef according to attack style

### ISSUE THREAD

**Issue by AlexxNino** [Loze-Put/hunllef-helper#19]
Change the tag color around the npc hunlef based on his attack style.

**Comment by Loze-Put** [comment]
Hi, thanks for your suggestion. I have been thinking about this feature request for a while. While it would be a nice addition, I think this feature would cross the border of what is allowed for a plugin like this. Pvm plugins in general are in a grey area. The core functionality of this plugin is against the third party statement by Jagex. The only fact allowing this plugin is that it is a completely seperate timer. It could be implemented outside of Runelite as it does not use any game state for its core functionality. Adding this feature would interact with the game itself. Thus at this point in time I'm not willing to risk it.
