### ISSUE TITLE
Lag Button

### ISSUE THREAD

**Issue by observnad** [Loze-Put/hunllef-helper#20]
If I created a pull request for the addition of a Lag button would it get merged? 

We all know the jegex servers are laggy at times and this results in hunllef falling behind the timer. Ideally the plugin would only progress on gametick but that has a chance to be against game rules. My idea was to add a lag button that would add an amount of additional delay on the current call out, similar to the trample button but on a smaller scale. 

The only issue is knowing how much lag occurred so im not sure how much of a delay the button should add. I'm thinking 1 gametick would be a good amount (600ms).

The current work around is to reset the help and wait for the next style swap.

**Comment by Loze-Put** [comment]
Thanks for your suggestion!

A PR is always welcome. Basing the timer off ticks would be very nice, but I don't want to go any further to the edge of what is allowed. It probably would be disallowed.

I have thought about this feature before. Personally I'd probably implement it with two buttons. A "+1 tick" and a "-1 tick" button. This also allows to speed up the timer in the case where someone started it slighty too late.

**Comment by Loze-Put** [comment]
I have published a new version of the plugin with these buttons added.
