### ISSUE TITLE
Plugin not apperearing in sidebar

### ISSUE THREAD

**Issue by griffo14** [Loze-Put/hunllef-helper#30]
Reoccurring problem with the hunllef helper plugin, i have tried everything for it to work, 'Automatically hide' is turned off, uninstalled and installed it again, still doesnt work, it has its moments when it wants to work and then when either runelite gets reset or updated, it just doesnt want to work, i rely on this plugin so badly haha, i just want the bowfa so i dont have to keep dealing with this rubbish lol. any suggestions?

**Comment by Loze-Put** [comment]
Does this issue occur just for this plugin, or for multiple plugins?
