### ISSUE TITLE
Question about delay 

### ISSUE THREAD

**Issue by chaggi1234** [Loze-Put/hunllef-helper#32]
Im having a problem with what seems to be de-sync? I start the timer on time but 2-3 waves in the timing is always a few hits early. It seems to be a problem only on my PC atm.. I tried using the plugin on my laptop and it works great. Anyone know a possible solution to what it may have been caused by and how to fix it?

**Comment by Loze-Put** [comment]
It is usually caused by server lag. I have added buttons to adjust the timer in a new version of the plugin. This should be available in-game in a couple of days.
