### ISSUE TITLE
Add "start mage" button

### ISSUE THREAD

**Issue by YvesW** [Loze-Put/hunllef-helper#4]
First of all, thanks for making the plugin; really love the way you implemented it!
I was wondering if you could also add a "start mage" button that does the same thing as the start button, except it starts with mage instead of ranged. I sometimes (regularly) forget to start it at the beginning. The easiest fix is starting it after 4 attacks in that case, but that results in the ranged/mage calls being wrong. It isn't such a huge problem, but seems like a nice QoL :)

Additionally, you could make the "I got trampled" button some shade of red/orange like Maz did, but not sure if such a big red button would look nice.

**Comment by Loze-Put** [comment]
Thank you for your suggestions. I will implement the "Start mage" button as it does seem very useful. It could also be used to more easily restart the plugin if the timing is off.

I'm not too sure about the recolor of the trampled button. I personally don't really like it, but tastes differ. I could make the color configurable.

**Comment by YvesW** [comment]
Thank you very much, that'd be awesome! Don't waste too much time on the color of the button; it's just a very minor thing.
Additionally, if you want to look into adding more timing controls, adding +1s/-1s (or +1 tick/-1 tick) buttons is a possibility. However, that might make the UI too cluttered, and I'm not sure if it'd be practical. Just throwing out some ideas if you want to experiment.

**Comment by Loze-Put** [comment]
I've thought about some buttons to adjust the time as well. My main worry was that the UI would get cluttered, or that someone would missclick a button and accidentally trample or reset the timer.
