### ISSUE TITLE
Needs update for Echo variant of boss

### ISSUE THREAD

**Issue by ShaunDreclin** [Loze-Put/hunllef-helper#47]
The echo hunllef changes attack styles faster than the regular one

https://github.com/user-attachments/assets/3d95789b-b62b-4136-85c9-e27cf0e9690b

**Comment by Loze-Put** [comment]
Hi,
Thanks for creating an issue. I expected the echo variant to be different from the main game Hunllef. I personally don't play Tirannwn in leagues so I am unable to update the plugin.
